#!/bin/bash
set +o history
unset "$HISTFILE"
BCI_API=
USE_TOR=
#
#Blah first run, about, menu.
#
## IS LOCKED
IS_LOCKED=$(ls | grep -c "KeyRNG.gpg")
if [ "$IS_LOCKED" -gt "0" ]; then
echo_c()
{
w=$(stty size | cut -d" " -f2)
l=${#1}
printf "%"$((l+(w-l)/2))"s\n" "$1"
}
  clear
  echo_c "-----------------------------------------"
  echo_c "| L O C K E D    K e y R N G    M E N U |"
  echo_c "-----------------------------------------"
  echo ""
  echo_c "$banr"
  echo ""
  PS3='Enter choice (press enter to see options again): '
  options=("Unlock KeyRNG Files" "Copy Encrypted Files For Backup" "About Locked File" "Quit")
  select opt in "${options[@]}"
  do
      case "$opt" in
          "Unlock KeyRNG Files")
unlock ()
{
read -s -p "Enter Password: " PW
PW=$(echo -n "$PW" | shasum -t -a 512 | cut -b -128)
gpg --quiet --no-use-agent --output checksum --passphrase "$PW" -d checksum.gpg
SUM=$(cat checksum)
CHK=$(cat keyrng | shasum -t -a 512 | cut -b -128)
if [ "$SUM" != "$CHK" ]; then
    echo -e "\nCHECKSUM OF keyrng DOES NOT MATCH FROM BEFORE LOCKING."
    echo "Do you still want to unlock your files? (Y/no)"
    read UNLOCK
    if [ "$UNLOCK" != "Y" ]; then
        gpg --passphrase "$PW" --no-use-agent --cipher-algo aes256 --symmetric checksum
        rm -rf checksum
        exit 0
    fi
fi
rm -rf checksum.gpg
gpg --quiet --no-use-agent --output KeyRNG.tar.gz --passphrase "$PW" -d KeyRNG.gpg
unset PW; unset CHKPW; unset SUM; unset CHKSUM
tar -xf KeyRNG.tar.gz
chown -R "$USER" * */ */*
chmod 0600 gpg-KeyRNG/gpg.conf
chmod 0600 btc-KeyRNG/*
echo "Shredding temp files..."
HAS_SRM=$(ls /usr/bin/ /usr/sbin/ /usr/local/bin/ | grep -c srm)
if [[ "$HAS_SRM" -gt "0" ]]; then
    srm -drlv checksum* KeyRNG.*
else
    shred -vuzn 3 checksum* KeyRNG.*
fi
}
                unlock
                break
                ;;
            "Copy Encrypted Files For Backup")
                clear
                echo "What would you like to path and/or name to be?"
                read BACKUP
                echo "Copying..."
                cp locked.KeyRNG "$BACKUP"
                echo "File is at "$BACKUP""
                echo "You should move it somewhere else if you would like to keep it."
                echo "Press enter to exit."
                read
                exit 0
                ;;
            "About Locked File")
                clear
                echo -e "\n\n$(ls -lh KeyRNG.locked)\n\n"
                ;;
            "Quit")
                exit 0
                ;;
        esac
    done
fi
## LIBRARY
. libkeyrng
## FIRST TIME
IS_FIRST_RUN=$(gpg --homedir gpg-KeyRNG/ --list-keys | grep -c KeyRNG)
if [ "$IS_FIRST_RUN" -lt "2" ]; then
    welcomemenu
    echo_c "Welcome to KeyRNG, a GnuPG and Bitcoin client and/or keyring."
    echo ""
    echo_c "Press enter to move on to initial setup."
    read
    clear
    firstrun
fi
## TEMP FILE
HAS_TEMP_FILE=$(ls | grep -c "temp")
if [ "$HAS_TEMP_FILE" -lt "1" ]; then
    mkdir temp/
fi
## MAIN MENU 
mainmenu
PS3='Enter choice (press enter to see options again): '
options=("GnuPG Management" "Bitcoin Management" "Quit" "FAST LOCK UP" "SECURE LOCK UP")
select opt in "${options[@]}"
do
    case "$opt" in
        "GnuPG Management")
        clear
        gpgmainmenu
        PS3='Enter choice (press enter to see options again): '
        options=("Key Management Menu" "Encryption Menu" "Decryption Menu" "Clearsign Menu" "BACK TO MAIN MENU" "Quit" "FAST LOCK UP" "SECURE LOCK UP")
        select opt in "${options[@]}"
        do
            case "$opt" in
                "Key Management Menu")
                    keymanagementmenu
                    PS3='Enter choice (press enter to see options again): '
                    options=("Generate New Keypair" "Public Keys" "Secret Keys" "BACK TO GPG MAIN MENU" "Quit" "FAST LOCK UP" "SECURE LOCK UP")
                    select opt in "${options[@]}"
                    do
                        case "$opt" in
                            "Generate New Keypair")
                                genkey
                                ;;
                            "Public Keys")
                                pubkeymenu
                                PS3='Enter choice (press enter to see options again): '
                                options=("List Pubkeys By UID" "List All Public Key Data" "Import Keys" "Export/Send Keys" "BACK TO KEY MANAGEMENT MENU" "Quit" "FAST LOCK UP" "SECURE LOCK UP")
                                select opt in "${options[@]}"
                                do
                                    case "$opt" in
                                        "List Pubkeys By UID")
                                            listkeyuids
                                            ;;
                                        "List All Public Key Data")
                                            listfullkeydetails
                                            ;;
                                        "Import Keys")
                                            importkeysmenu
                                            PS3='Enter choice (press enter to see options again): '
                                            options=("Receive From Keyserver" "Import Public Key From File" "Import Public Key From Clipboard" "Import Single Key From Another GPG" "Import All Public Keys From Another GPG" "Refresh Keys From Keyserver" "BACK TO PUBLIC KEYS MENU" "Quit" "FAST LOCK UP" "SECURE LOCK UP")
                                            select opt in "${options[@]}"
                                            do
                                                case "$opt" in
                                                    "Receive From Keyserver")
                                                        recvkeyserv
                                                        ;;
                                                    "Import Public Key From File")
                                                        importkeyfile
                                                        ;;
                                                    "Import Public Key From Clipboard")
                                                        importkeyclip
                                                        ;;
                                                    "Import Single Key From Another GPG")
                                                        importkeyfromgpg
                                                        ;;
                                                    "Import All Public Keys From Another GPG")
                                                        gpgimportallpub
                                                        ;;
                                                    "Refresh Keys From Keyserver")
                                                        refreshkeys
                                                        ;;
                                                    "BACK TO PUBLIC KEYS MENU")
                                                        break
                                                        ;;
                                                    "Quit")
                                                        badquit
                                                        ;;
                                                    "FAST LOCK UP")
                                                        fastlockup
                                                        ;;
                                                    "SECURE LOCK UP")
                                                        lockup
                                                        ;;
                                                    *) echo "Invalid Option";;
                                                esac
                                            done
                                            ;;
                                        "Export/Send Keys")
                                        exportkeysmenu
                                        PS3='Enter choice (press enter to see options again): '
                                        options=("Send To Keyserver" "Print Pubkey Here" "Export Pubkey To File" "BACK TO PUBLIC KEYS MENU" "Quit" "FAST LOCK UP" "SECURE LOCK UP")
                                        select opt in "${options[@]}"
                                        do
                                            case "$opt" in
                                                "Send To Keyserver")
                                                    sendkeyserv
                                                    ;;
                                                "Print Pubkey Here")
                                                    exportpubkey
                                                    ;;
                                                "Export Pubkey To File")
                                                    exportpubkeyfile
                                                    ;;
                                                "BACK TO PUBLIC KEYS MENU")
                                                    break
                                                    ;;
                                                "Quit")
                                                    badquit
                                                    ;;
                                                "FAST LOCK UP")
                                                    fastlockup
                                                    ;;
                                                "SECURE LOCK UP")
                                                    lockup
                                                    ;;
                                                *) echo "Invalid Option";;
                                            esac
                                        done
                                            ;;
                                        "BACK TO KEY MANAGEMENT MENU")
                                            break
                                            ;;
                                        "Quit")
                                            badquit
                                            ;;
                                        "FAST LOCK UP")
                                            fastlockup
                                            ;;
                                        "SECURE LOCK UP")
                                            lockup
                                            ;;
                                        *) echo "Invalid Option";;
                                    esac
                                done
                                ;;
                            "Secret Keys")
                                clear
                                seckeysmenu
                                PS3='Enter choice (press enter to see options again): '
                                options=("Import Secret Keys" "List Secret Keys By UID" "List Full Secret Key Info" "Export Secret Key To Terminal" "Export Secret Key To File" "BACK TO KEY MANAGEMENT MENU" "Quit" "FAST LOCK UP" "SECURE LOCK UP")
                                select opt in "${options[@]}"
                                do
                                    case "$opt" in
                                        "Import Secret Keys")
                                        importseckeysmenu
                                        PS3='Enter choice (press enter to see options again): '
                                        options=("Import A Secret Key From Another GPG" "Import All Secret Keys From Another GPG" "Import From File" "Import From Clipboard" "BACK TO SECRET KEYS MENU" "Quit" "FAST LOCK UP" "SECURE LOCK UP")
                                        select opt in "${options[@]}"
                                        do
                                            case "$opt" in
                                                "Import A Secret Key From Another GPG")
                                                    importseckeyfromgpg
                                                    ;;
                                                "Import All Secret Keys From Another GPG")
                                                    gpgimportallsec
                                                    ;;
                                                "Import From File")
                                                    importkeyfile
                                                    ;;
                                                "Import From Clipboard")
                                                    importkeyclip
                                                    ;;
                                                "BACK TO SECRET KEYS MENU")
                                                    break
                                                    ;;
                                                "Quit")
                                                    badquit
                                                    ;;
                                                "FAST LOCK UP")
                                                    fastlockup
                                                    ;;
                                                "SECURE LOCK UP")
                                                    lockup
                                                    ;;
                                                *) echo "Invalid Option";;
                                            esac
                                        done
                                            ;;
                                        "List Secret Keys By UID")
                                            listseckeyuid
                                            ;;
                                        "List Full Secret Key Info")
                                            listfullseckey
                                            ;;
                                        "Export Secret Key To Terminal")
                                            exportseckey
                                            ;;
                                        "Export Secret Key To File")
                                            exportseckeyfile
                                            ;;
                                        "BACK TO KEY MANAGEMENT MENU")
                                            break
                                            ;;
                                        "Quit")
                                            badquit
                                            ;;
                                        "FAST LOCK UP")
                                            fastlockup
                                            ;;
                                        "SECURE LOCK UP")
                                            lockup
                                            ;;
                                        *) echo "Invalid Option";;
                                        esac
                                    done
                                    ;;
                                "BACK TO GPG MAIN MENU")
                                    break
                                    ;;
                                "Quit")
                                    badquit
                                    ;;
                                "FAST LOCK UP")
                                    fastlockup
                                    ;;
                                "SECURE LOCK UP")
                                    lockup
                                    ;;
                                *) echo "Invalid Option";;
                            esac
                        done
                        ;;
                    "Encryption Menu")
                        encryptmenu
                        PS3='Enter choice (press enter to see options again): '
                        options=("Encrypt A File" "Encrypt A New Message" "BACK TO GPG MENU" "Quit" "FAST LOCK UP" "SECURE LOCK UP")
                        select opt in "${options[@]}"
                        do
                            case "$opt" in
                                "Encrypt A File")
                                    encryptfile
                                    ;;
                                "Encrypt A New Message")
                                    encryptnewmsg
                                    ;;
                                "BACK TO GPG MENU")
                                    break
                                    ;;
                                "Quit")
                                    badquit
                                    ;;
                                "FAST LOCK UP")
                                    fastlockup
                                    ;;
                                "SECURE LOCK UP")
                                    lockup
                                    ;;
                                *) echo "Invalid Option";;
                            esac
                        done
                        ;;
                    "Decryption Menu")
                        decryptmenu
                        PS3='Enter choice (press enter to see options again): '
                        options=("Decrypt From A File" "Decrypt From Clipboard" "BACK TO GPG MENU" "Quit" "FAST LOCK UP" "SECURE LOCK UP")
                        select opt in "${options[@]}"
                        do
                            case "$opt" in
                                "Decrypt From A File")
                                    decryptfile
                                    ;;
                                "Decrypt From Clipboard")
                                    decryptclip
                                    ;;
                                "BACK TO GPG MENU")
                                    break
                                    ;;
                                "Quit")
                                    badquit
                                    ;;
                                "FAST LOCK UP")
                                    fastlockup
                                    ;;
                                "SECURE LOCK UP")
                                    lockup
                                    ;;
                                *) echo "Invalid Option";;
                            esac
                        done
                        ;;
                    "Clearsign Menu")
                        clearsignmenu
                        PS3='Enter option (press enter to show options again): '
                        options=("Clearsign From File" "Clearsign New Message" "Verify Clearsigned File" "Verify Clearsigned Message From Clipboard" "BACK TO GPG MENU" "Quit" "FAST LOCK UP" "SECURE LOCK UP")
                        select opt in "${options[@]}"
                        do
                            case "$opt" in
                                "Clearsign From File")
                                    csignfile
                                    ;;
                                "Clearsign New Message")
                                    csignnew
                                    ;;
                                "Verify Clearsigned File")
                                    gpgfileverify
                                    ;;
                                "Verify Clearsigned Message From Clipboard")
                                    gpgclipverify
                                    ;;
                                "BACK TO GPG MENU")
                                    break
                                    ;;
                                "Quit")
                                    badquit
                                    ;;
                                "FAST LOCK UP")
                                    fastlockup
                                    ;;
                                "SECURE LOCK UP")
                                    lockup
                                    ;;
                                *) echo "Invalid Option";;
                            esac
                        done
                        ;;
                    "BACK TO MAIN MENU")
                        break
                        ;;
                    "Quit")
                        badquit
                        ;;
                    "FAST LOCK UP")
                        fastlockup
                        ;;
                    "SECURE LOCK UP")
                        lockup
                        ;;
                    *) echo "Invalid option";;
                esac
            done
            ;;
        "Bitcoin Management")
            HAS_BTCFILE=$(ls | grep -c "btc-KeyRNG")
            if [ "$HAS_BTCFILE" -lt "1" ]; then
                mkdir btc-KeyRNG
                chown "$USER" btc-KeyRNG/
            fi
            ENC_BTCFILE=$(ls | grep -c "btc.tar.gz.gpg")
            if [ "$ENC_BTCFILE" -gt "0" ]; then
                echo "Bitcoin file is locked."
                echo "Press enter to decrypt."
                read
                gpg2 --output btc.tar.gz --decrypt btc.tar.gz.gpg
                tar -x btc.tar.gz
                echo "Shredding old file..."
                DEL=*tar.gz*
                secdelete
            fi
            haspriv
            mainbtcmenu
            PS3='Enter option (press enter to see options again): '
            options=("Address Management" "Show All Addresses" "Blockchain Interaction" "Sign Message" "BACK TO MAIN MENU" "Quit" "FAST LOCK UP" "SECURE LOCK UP")
            select opt in "${options[@]}"
            do
                case "$opt" in
                    "Address Management")
                    addrmanagemenu
                    PS3='Enter option (press enter to see options again): '
                    options=("Standard Addresses Menu" "Electrum Addresses Menu" "BIP32 Addresses Menu" "Multisig Addresses Menu" "BACK TO BITCOIN MANAGEMENT MENU" "Quit" "FAST LOCKUP!" "SECURE LOCKUP!")
                    select opt in "${options[@]}"
                    do
                      case "$opt" in
                       "Standard Addresses Menu")
                       standaddrmenu
                       PS3='Enter option (press enter to see options again): '
                       options=("Create New Address" "Create Multiple New Addresses" "Show Addresses Only" "Show Addresses And Pubkeys" "Show Private Keys" "BACK TO ADDRESS MGMT MENU" "Quit" "FAST LOCK UP" "SECURE LOCK UP")
                       select opt in "${options[@]}"
                       do
                           case "$opt" in
                               "Create New Address")
                                   getnewaddress
                                   ;;
                               "Create Multiple New Addresses")
                                   multiplestandaddr
                                   ;;
                               "Show Addresses Only")
                                   showaddr
                                   ;;
                               "Show Addresses And Pubkeys")
                                   showallstandaddr
                                   ;;
                               "Show Private Keys")
                                   showstandardpriv
                                   ;;
                               "BACK TO ADDRESS MGMT MENU")
                                   break
                                   ;;
                               "Quit")
                                   badquit
                                   ;;
                               "FAST LOCK UP")
                                   fastlockup
                                   ;;
                               "SECURE LOCK UP")
                                   lockup
                                   ;;
                               *) echo "Invalid Option";;
                           esac
                       done
                       ;;
                       "Electrum Addresses Menu")
                           checkeleseed
                           eleaddrmenu
                           PS3='Enter choice (press enter to see options again): '
                           options=("Create New Address" "Create Multiple Addresses" "Show Addresses Only" "Show Addresses And Pubkeys" "Show Private Keys" "Show Seed" "BACK TO ADDRESS MGMT MENU" "Quit" "FAST LOCK UP" "SECURE LOCK UP")
                           select opt in "${options[@]}"
                           do
                               case "$opt" in
                                   "Create New Address")
                                       elecreateaddr
                                       ;;
                                   "Create Multiple Addresses")
                                       multipleeleaddr
                                       ;;
                                   "Show Addresses Only")
                                       eleshowaddr
                                       ;;
                                   "Show Addresses And Pubkeys")
                                       eleshowall
                                       ;;
                                   "Show Private Keys")
                                       showelepriv
                                       ;;
                                   "Show Seed")
                                       eleshowseed
                                       ;;
                                   "BACK TO ADDRESS MGMT MENU")
                                       break
                                       ;;
                                   "Quit")
                                       badquit
                                       ;;
                                   "FAST LOCK UP")
                                       fastlockup
                                       ;;
                                   "SECURE LOCK UP")
                                       lockup
                                       ;;
                                   *) echo "Invalid Option";;
                               esac
                           done                        
                           ;;
                       "BIP32 Addresses Menu")
                           checkbipseed
                           bipaddrmenu
                           PS3='Enter choice (press enter to see options again): '
                           options=("Create New Address" "Create Multiple Addresses" "Show Addresses Only" "Show Addresses And Pubkeys" "Show Private Keys" "Show Seed" "BACK TO ADDRESS MGMT MENU" "Quit" "FAST LOCK UP" "SECURE LOCK UP")
                           select opt in "${options[@]}"
                           do
                               case "$opt" in
                                   "Create New Address")
                                       bipcreateaddr
                                       ;;
                                   "Create Multiple Addresses")
                                       multiplebipaddr
                                       ;;
                                   "Show Addresses Only")
                                       bipshowaddr
                                       ;;
                                   "Show Addresses And Pubkeys")
                                       bipshowall
                                       ;;
                                   "Show Private Keys")
                                       bipshowpriv
                                       ;;
                                   "Show Seed")
                                       bipshowseed
                                       ;;
                                   "BACK TO ADDRESS MGMT MENU")
                                       break
                                       ;;
                                   "Quit")
                                       badquit
                                       ;;
                                   "FAST LOCK UP")
                                       fastlockup
                                       ;;
                                   "SECURE LOCK UP")
                                       lockup
                                       ;;
                                   *) echo "Invalid Option";;
                               esac
                           done                        
                           ;;
                       "Multisig Addresses Menu")
                           multisigmenu
                           PS3='Enter choice (press enter to see options again): '
                           options=("New Multisig Address/Script" "Show All Multisig Address/Scripts" "BACK TO ADDRESS MGMT MENU" "Quit" "FAST LOCKUP!" "SECURE LOCKUP!")
                           select opt in "${options[@]}"
                           do
                             case "$opt" in
                               "New Multisig Address/Script")
                                   makemultisigaddr
                                   ;;
                               "Show All Multisig Address/Scripts")
                                   showmsaddr
                                   ;;
                               "BACK TO ADDRESS MGMT MENU")
                                   break
                                   ;;
                               "Quit")
                                   badquit
                                   ;;
                               "FAST LOCKUP!")
                                   fastlockup
                                   ;;
                               "SECURE LOCKUP!")
                                   lockup
                                   ;;
                               *) echo "Invalid Option";;
                             esac
                           done
                           ;;
                       "BACK TO BITCOIN MANAGEMENT MENU")
                           break
                           ;;
                       "Quit")
                           badquit
                           ;;
                       "FAST LOCKUP!")
                           fastlockup
                           ;;
                       "SECURE LOCKUP!")
                           lockup
                           ;;
                       *) echo "Invalid Option";;
                      esac
                    done
                    ;;
                    "Show All Addresses")
                        showalladdr
                        ;;
                    "Blockchain Interaction")
                    HA=$(echo "$BCI_API" | grep -c "")
                    if  [ "$HA" -gt "0" ]; then
                      HAVE_API=y
                    fi
                    RAN=$(echo -n "$USE_TOR" | grep -c "")
                    if [ "$RAN" = "0" ]; then
                        echo -e "\nKeyRNG is using the Blockchain.info API for blockchain interaction."
                        echo "Tor users go through BCIs hidden service."
                        echo -e "\nRoute your requests through tor? (y/no)"
                        read USE_TOR
                        echo -e "\nWithout an API key you may get rate limiting errors."
                        echo "Do you have a BCI API key? (y/no)"
                        read HAVE_API
                        if [ "$HAVE_API" = "y" ]; then
                            echo "Paste key."
                            read BCI_API
                        fi
                    fi
                    bcimenu
                    PS3='Enter option (press enter to see options again): '
                    options=("Make/Send Transaction" "Check Unspent Balance" "Raw Transaction Details" "Raw Address History" "Show All Addresses And Pubkeys" "BACK TO BITCOIN MGMT MENU" "Quit" "FAST LOCK UP" "SECURE LOCK UP")
                    select opt in "${options[@]}"
                    do
                        case "$opt" in
                            "Make/Send Transaction")
                                mktx
                                ;;
                            "Check Unspent Balance")
                                checkunspent
                                ;;
                            "Raw Transaction Details")
                                getrawtx
                                ;;
                            "Raw Address History")
                                rawaddrhist
                                ;;
                            "Show All Addresses And Pubkeys")
                                showalladdr
                                ;;
                            "BACK TO BITCOIN MGMT MENU")
                                break
                                ;;
                            "Quit")
                                badquit
                                ;;
                            "FAST LOCK UP")
                                fastlockup
                                ;;
                            "SECURE LOCK UP")
                                lockup
                                ;;
                            *) echo "Invalid Option";;
                        esac
                    done
                        ;;
                    "Sign Message")
                        btcsign
                        ;;
                    "BACK TO MAIN MENU")
                        break
                        ;;
                    "Quit")
                        badquit
                        ;;
                    "FAST LOCK UP")
                        fastlockup
                        ;;
                    "SECURE LOCK UP")
                        lockup
                        ;;
                    *) echo "Invalid Option";;
                esac
            done
             ;;
        "Quit")
            badquit
            ;;
        "FAST LOCK UP")
            fastlockup
            ;;  
        "SECURE LOCK UP")
            lockup
            ;;
        *) echo "Invalid Option";;
    esac
done
